### ISSUE TITLE
mysterious hydrofunctions_testing.log

### ISSUE THREAD

**Issue by mlr07** [mroberge/hydrofunctions#109]
* HydroFunctions version: 0.2.1
* Python version: 3.8.10
* Operating System: Linux Mint 20.04

### Description
A `hydrofunctions_testing.log` is created when importing `hydrofunctions` into a jupyter cell or python script. what is the source of this log? Can it be suppressed?

### What I Did

In jupyter cell:
```
import hydrofunctioons
```
From terminal:
```
(hydro) mlr@mint-box:~/git/hydro-tools$ ls | grep hydro*.log
hydrofunctions_testing.log
```

**Comment by mroberge** [comment]
Thank you for filing this issue!
I created this log file to help diagnose some issues I had when determining the frequency of a timeseries. There is no need for it for most users, so I'm going to get rid of it from the codebase.

Nice catch! Thank you!
-Marty

**Comment by mroberge** [comment]
I fixed up the logging a little bit- it now has a better message format, errors and warnings from hydrofunctions are logged automatically, the log file is named "hydrofunctions.log". There is no logging by default. Use hf._start_logging() to start collecting logs.
Closing this issue.
Thanks for filing this, @mlr07 !

**Comment by mlr07** [comment]
no worries, glad I could help out!
