### ISSUE TITLE
Problem with extract_nwis_df

### ISSUE THREAD

**Issue by DavidLitwin** [mroberge/hydrofunctions#48]
* HydroFunctions version: 0.1.7
* Python version: 3.6.6 64-bit
* Operating System: Windows 10

### Description
I'm trying to import NWIS data, just as in the sample code, and an error is returned from the extract_nwis_df function. Any ideas what the problem might be?

### What I Did

```
import hydrofunctions as hf

site = '01646000'
start_date = '2017-10-01'
end_date = '2018-10-01'

response = hf.get_nwis(site,'iv', start_date,end_date,parameterCd='00060')
response.json()
hf.extract_nwis_df(response)
=========================================
Traceback (most recent call last):

  File "<ipython-input-1-01f3848c24e4>", line 15, in <module>
    hf.extract_nwis_df(response)

  File "C:\Users\dgbli\Anaconda3\lib\site-packages\hydrofunctions\hydrofunctions.py", line 277, in extract_nwis_df
    ts = nwis_dict['value']['timeSeries']

TypeError: 'Response' object is not subscriptable

```

**Comment by mroberge** [comment]
Hi @DavidLitwin !
Thank you for using HydroFunctions. I apologize, but it looks like I may have updated the interface to hydrofunctions, but haven't updated the documentation. I've actually just made a major change for 0.1.8 that will really improve the user experience, so I haven't worked too hard on fixing all of the old documentation.  Anyway, that's no excuse!

Here is what you can do to get yourself a dataframe of hydrology data:

```python
import hydrofunctions as hf

site = '01646000'
start_date = '2017-10-01'
end_date = '2018-10-01'

response = hf.get_nwis(site,'iv', start_date,end_date,parameterCd='00060')
my_dataframe = hf.extract_nwis_df(response.json())

my_dataframe
```
... and this will produce a nice listing of your new dataframe.

Good luck, and let me know if you have any further trouble!

**Comment by DavidLitwin** [comment]
Ah, easy enough, thank you. Another question - is there capability to download multiple parameters in the same call? Say:

`response = hf.get_nwis(site,'iv', start_date,end_date,parameterCd=['00060','99133','63680'])`

Thanks!

**Comment by mroberge** [comment]
I can't remember if you can do that in 0.1.7, but the new version defaults to request everything collected at a site, and you can list multiple parameters. Unfortunately, you would have to install it from the develop branch on GitHub, because it's not on pypi yet.

**Comment by DavidLitwin** [comment]
I'm sorry, I'm new to github so I'm still trying to figure this out. I've just tried to install it with:
`pip install git+https://github.com/mroberge/hydrofunctions.git@develop`
But it seems to give me just version 0.1.7. Am I doing something wrong? Thanks for your help.

**Comment by mroberge** [comment]
Actually, you have the latest material by installing from Develop, but I didn't modify the version number yet. I usually do that when I finally post everything onto PyPI.

Try loading new data this way (if you don't specify what parameter you want, you'll get every parameter measured at this site:
```python
my_data = hf.NWIS(['01585200','03543500'] 'iv', period='P100D')
```
This will print out what you have loaded:
```python
my_data
```
and this will give you a dataframe of just the discharge data:
```python
my_data.df('Q')
```
If you save the discharge dataframe to a variable, then it is easy to use the Pandas convenience methods, like `.plot()` or `.describe()`.

**Comment by DavidLitwin** [comment]
Thanks, got it working!
