### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by mroberge** [mroberge/hydrofunctions#75]
* HydroFunctions version: 0.2.0

### Description

There are two changes to setup.py that need to be made:

- nbsphinx does not need to be listed in setup.py
- pyarrow should no longer be fixed to 0.16.0

**Comment by mroberge** [comment]
Also, why is IPython listed in the requirements? I meant this to make it easy for new users: if you installed hydrofunctions, then must have Jupyter notebooks installed too. But you can run JupyterLab from the (base) environment, and run kernals from another environment.

So what do I do? 

Perhaps it makes most sense to tell users to install Anaconda, and then `pip install hydrofunctions`. Remove IPython and similar requirements from setup.py

**Comment by kylebluenote** [comment]
Hi! I just wanted to check in and see if there was a plan to update these dependencies.  We utilize hydrofunctions (and like it!), but need to bump pyarrow to 0.17.0 due to some issues, which is causing a dependency issue.

**Comment by mroberge** [comment]
Thank you! It's great to hear from you!

I pinned pyarrow to 0.17.1 in the Develop branch. Try using that branch and see if it works with everything else that you are using. If it does, then I can push that to Master and publish a new version for you. Let me know if you want a description of how to install from the Develop branch directly from Github.

Good luck!

**Comment by kylebluenote** [comment]
Awesome, thank you!  I'm trying to install (using pipenv), where my pipfile has
```
-hydrofunctions = "==0.2.0"
+hydrofunctions = {editable = true,git = "https://github.com/mroberge/hydrofunctions.git",ref = "develop"}
```
but I get the error described in https://github.com/pypa/pipenv/issues/4375

**Comment by kylebluenote** [comment]
Hey @mroberge we just finished up some testing and things look like they're working for us!

**Comment by mroberge** [comment]
That's excellent! I will try to release a new version in a week so you can install from pypi again.
I'd love to see how you're using hydrofunctions! You should post a Jupyter notebook to github.

**Comment by kylebluenote** [comment]
Awesome, thank you!  I'll take a closer look at some of our internal uses and see if we can publish them to share.
